### ISSUE TITLE
`ziti` cannot supply 'limit' nor 'offset'

### ISSUE THREAD

**Issue by dovholuknf** [netfoundry/ziti-cmd#57]
When using `ziti` one cannot supply a 'limit'. This means when using `ziti` against an instance with > 10 objects one is trying to query results are missing. Also since one cannot specify offset - when used against really really large number of objects those also will not be findable.

**Comment by plorenz** [comment]
I would propose that for the v1 API that @andrewpmartinez is kicking off, that we allow limit/offset to be passed in as part of the filter, since the filter language supports that now. That will simplify the APIs somewhat and since you can pass in filters with `ziti` won't require any client side changes.
